version: '3.1'

services:
    db:
        image: mysql@sha256:43bf7db32d11e75d8463a8bc077f09af5fb5b84b182b1d74124ddca633093bfa
        command: >
            --charactor-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_DATABASE: youtube
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: pass
            TZ: 'Asia/Tokyo'
        ports: 
            - "13306:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata: